title = "MQTT Observing Conditions"

[network]
ip_address = ''             # Any address
port = 5555

[server]
location = 'Maurertown, Virginia, USA'  # Anything you want here
verbose_driver_exceptions = true

[device]
mqtt_port = 1883
topic_cloud_cover = 'weather/cloudCover'
topic_wind_speed_avg = 'weather/windspdkmh_avg10m'
topic_event_rain = 'weather/eventrainmm'
topic_probability_of_precipitation = 'forecast/probability_of_precipitation'
topic_forecast_precipitation = 'forecast/precipitation_mount'
topic_rain_in_region = 'weather/rain_in_region'
limit_precipation_probability = 5

[logging]
log_level = 'INFO'
log_to_stdout = true
max_size_mb = 5
num_keep_logs = 10
